version: '2'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: telecom-db-dev
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrongPassword123!"
      MSSQL_ALLOW_RUNNING_AS_ROOT: "1"
    ports:
      - "1433:1433"
    restart: unless-stopped